app:
    resource: "@FrontBundle/Controller/"
    type:     annotation

# FOS User
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Sonata
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"

# Sonata custom routes
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin